services:
  pgvector_db:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: pgvector_db
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - backend
    
    restart: always


networks:
  backend:
volumes:
  pgvector_data: