"""update schema

Revision ID: 0700ac9eefa2
Revises: initial_schema
Create Date: 2025-09-13 19:03:05.803120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0700ac9eefa2'
down_revision: Union[str, Sequence[str], None] = 'initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_uuid')
    )
    op.create_table('assets',
    sa.Column('asset_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_uuid', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('asset_name', sa.String(), nullable=False),
    sa.Column('asset_size', sa.Integer(), nullable=False),
    sa.Column('asset_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('asset_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('asset_id'),
    sa.UniqueConstraint('asset_uuid')
    )
    op.create_table('jobpostings',
    sa.Column('jobposting_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jobposting_uuid', sa.UUID(), nullable=False),
    sa.Column('job_title', sa.String(), server_default='Unknown', nullable=False),
    sa.Column('company_name', sa.String(), server_default='Unknown', nullable=False),
    sa.Column('skills', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('recruiter_email', sa.String(), nullable=True),
    sa.Column('post_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('jobposting_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['jobposting_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('jobposting_id'),
    sa.UniqueConstraint('jobposting_uuid')
    )
    op.drop_table('projects')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('project_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_uuid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('project_id', name=op.f('projects_pkey'))
    )
    op.drop_table('jobpostings')
    op.drop_table('assets')
    op.drop_table('users')
    # ### end Alembic commands ###
