"""empty message

Revision ID: 514ff23a4653
Revises: f62ab3da0615
Create Date: 2025-09-22 10:20:40.496609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '514ff23a4653'
down_revision: Union[str, Sequence[str], None] = 'f62ab3da0615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('experience', 'start_date',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('experience', 'end_date',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('experience', 'end_date',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('experience', 'start_date',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
