"""Adding experience_type to Experience Model

Revision ID: 66841a273833
Revises: c84069ae6000
Create Date: 2025-09-25 15:40:12.053631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66841a273833'
down_revision: Union[str, Sequence[str], None] = 'c84069ae6000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience', sa.Column('experience_type', sa.String(), nullable=False))
    op.alter_column('experience', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('experience', 'skills',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('experience', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('experience', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('experience', 'skills',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('experience', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('experience', 'experience_type')
    # ### end Alembic commands ###
