"""updated experience schema

Revision ID: a59ce822d44c
Revises: a46b5d397584
Create Date: 2025-09-21 14:36:38.505492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a59ce822d44c'
down_revision: Union[str, Sequence[str], None] = 'a46b5d397584'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience', sa.Column('experience_asset_id', sa.Integer(), nullable=False))
    op.add_column('experience', sa.Column('skills', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('experience', sa.Column('experience_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('experience', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('experience_asset_id_fkey'), 'experience', type_='foreignkey')
    op.create_foreign_key(None, 'experience', 'assets', ['experience_asset_id'], ['asset_id'])
    op.drop_column('experience', 'asset_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience', sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'experience', type_='foreignkey')
    op.create_foreign_key(op.f('experience_asset_id_fkey'), 'experience', 'assets', ['asset_id'], ['asset_id'])
    op.alter_column('experience', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('experience', 'experience_metadata')
    op.drop_column('experience', 'skills')
    op.drop_column('experience', 'experience_asset_id')
    # ### end Alembic commands ###
