"""initialising alembic

Revision ID: a5deca15f1e0
Revises: 
Create Date: 2025-09-09 09:36:28.489413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5deca15f1e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('project_id'),
    sa.UniqueConstraint('project_uuid')
    )
    op.create_table('assets',
    sa.Column('asset_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_uuid', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('asset_name', sa.String(), nullable=False),
    sa.Column('asset_size', sa.Integer(), nullable=False),
    sa.Column('asset_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('asset_project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('asset_id'),
    sa.UniqueConstraint('asset_uuid')
    )
    op.create_table('chunks',
    sa.Column('chunk_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chunk_uuid', sa.UUID(), nullable=False),
    sa.Column('chunk_text', sa.String(), nullable=False),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('chunk_order', sa.Integer(), nullable=False),
    sa.Column('chunk_project_id', sa.Integer(), nullable=False),
    sa.Column('chunk_asset_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chunk_asset_id'], ['assets.asset_id'], ),
    sa.ForeignKeyConstraint(['chunk_project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('chunk_id'),
    sa.UniqueConstraint('chunk_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chunks')
    op.drop_table('assets')
    op.drop_table('projects')
    # ### end Alembic commands ###
