"""Adding jobposting-asset relation

Revision ID: c84069ae6000
Revises: 514ff23a4653
Create Date: 2025-09-25 15:01:22.611374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c84069ae6000'
down_revision: Union[str, Sequence[str], None] = '514ff23a4653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobpostings', sa.Column('jobposting_asset_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'jobpostings', 'assets', ['jobposting_asset_id'], ['asset_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobpostings', type_='foreignkey')
    op.drop_column('jobpostings', 'jobposting_asset_id')
    # ### end Alembic commands ###
