"""Adding foreign key to User-Experience tables

Revision ID: edf089a82736
Revises: a59ce822d44c
Create Date: 2025-09-21 15:26:29.496147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edf089a82736'
down_revision: Union[str, Sequence[str], None] = 'a59ce822d44c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience', sa.Column('experience_user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'experience', 'users', ['experience_user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'experience', type_='foreignkey')
    op.drop_column('experience', 'experience_user_id')
    # ### end Alembic commands ###
