from enum import Enum


class ResponseSignal(Enum):

    POSTING_SIZE_EXCEEDED = "POSTING_size_exceeded"
    POSTING_EXTENSION_UNSUPPORTED = "POSTING_extension_unsupported"
    POSTING_VALIDATION_SUCESS = "POSTING_successfuly_validated"
    POSTING_UPLOAD_FAIL ="POSTING_upload_failed"
    POSTING_UPLOAD_SUCCESS = "POSTING_upload_sucess"
    POSTING_ID_ERROR = "POSTING_id_error"
    NO_POSTINGS_ERROR = "no_POSTINGs_error"
    POSTING_ID_NOT_PROVIDED_ERROR = "POSTING_id_not_provided_error"
    POSTING_PROCESSING_SUCCESS = "POSTING_PROCESSING_SUCCESS"
    POSTING_PROCESSING_FAIL = "POSTING_PROCESSING_FAIL"

#### EXPERIENCE PROCESSING ENUMS
    EXPERIENCE_SIZE_EXCEEDED = "EXPERIENCE_SIZE_EXCEEDED"
    EXPERIENCE_EXTENSION_UNSUPPORTED = "EXPERIENCE_EXTENSION_UNSUPPORTED"
    EXPERIENCE_VALIDATION_SUCESS = "EXPERIENCE_VALIDATION_SUCESS"
    EXPERIENCE_UPLOAD_FAIL ="EXPERIENCE_UPLOAD_FAIL"
    EXPERIENCE_UPLOAD_SUCCESS = "EXPERIENCE_UPLOAD_SUCCESS"
    EXPERIENCE_ID_ERROR = "EXPERIENCE_ID_ERROR"
    NO_EXPERIENCES_ERROR = "NO_EXPERIENCES_ERROR"
    EXPERIENCE_ID_NOT_PROVIDED_ERROR = "EXPERIENCE_ID_NOT_PROVIDED_ERROR"   
    EXPERIENCE_PROCESSING_SUCCESS = "EXPERIENCE_PROCESSING_SUCCESS"
    EXPERIENCE_PROCESSING_FAIL = "EXPERIENCE_PROCESSING_FAIL"

#### Suggestion ENUMS

    JOBPOSTING_NOT_FOUND = "JOBPOSTING_NOT_FOUND"
    PULLING_EXPERIENCE_ERROR = "PULLING_EXPERIENCE_ERROR"